//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TblEducation
    {
        public int id { get; set; }
        [Required(ErrorMessage = "You must fill this field!")]
        public string title { get; set; }
        public string subtitle { get; set; }
        public string department { get; set; }
        public string gpa { get; set; }
        public string date { get; set; }
    }
}
